version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: ASMPID-2025
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    restart: always
